# .goreleaser.yaml
version: 2
project_name: span-report-collector

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    dir: ./dist
    main: ./main.go
    binary: span-report-collector
