version: 2
project_name: span-report-collector

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - README-ja.md
      - LICENSE
      - config.yaml
      - span-report-collector.service
      - tui.png
      - diagram-ja.png
      - diagram-en.png

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    dir: ./dist
    binary: span-report-collector
dist: releases
